aws_region           = "us-east-1"
ecr_repository_name  = "first-repository"
s3_bucket_name       = "manas-ecr-terraform-state-bucket123"
state_file_key       = "terraform/state.tfstate"
dynamodb_table_name  = "ecr-terraform-locks"
